Fix `The "-p" option does not exist.` issue
Run composer update --with='laravel/framework:^9.0' --no-interaction --no-progress -prefer-dist --prefer-stable --prefer-lowest
  composer update --with='laravel/framework:^9.0' --no-interaction --no-progress -prefer-dist --prefer-stable --prefer-lowest
  shell: /usr/bin/bash -e {0}
  env:
    COMPOSER_PROCESS_TIMEOUT: 0
    COMPOSER_NO_INTERACTION: 1
    COMPOSER_NO_AUDIT: 1
Error: The "-p" option does not exist.

  The "-p" option does not exist.